### PR TITLE
Add typings for V2

### PR DESCRIPTION
**Pull request by KubaJastrz**
I've also added `typescript` as a dev dependency for typechecking. I'm planning to rewrite the package to TS soon anyways.

### CODE REVIEW

**Comment by atomiks** [comment]
Is `<Tippy />` an exotic forward ref component too? (I mean I have no idea, but the default export is wrapperd in `forwardRef` now)

**Comment by KubaJastrz** [comment]
Good catch, they should be the other way around 😅 
TippyGroup is just a regular function component, while Tippy is an exotic forward ref component.

**Comment by RoberMac** [comment]
Also need to update the samples of README, like:

```tsx
export const Tooltip = forwardRef(
  props => <Tippy {...props} />
)
Tooltip.defaultProps = {
  animation: 'fade',
  arrow: true,
  delay: 150,
  theme: 'translucent',
}

export const Popover = forwardRef(
  props => <Tippy {...props} />
)
Popover.defaultProps = {
  animateFill: false,
  animation: 'scale',
  interactive: true,
  interactiveBorder: 10,
  theme: 'light-border',
  trigger: 'click',
}

// In another file
import { Tooltip, Popover } from './Tippy'
```

**Comment by atomiks** [comment]
@RoberMac not sure what you mean, they work without `forwardRef`

**Comment by RoberMac** [comment]
```tsx
export const Popover: React.ForwardRefExoticComponent<TippyProps> = props => <Tippy {...props} />
```

Use as above will throw TS error:

```
Property '$$typeof' is missing in type '{ (props: TippyProps): Element; defaultProps: { arrow: true; interactive: true; distance: number; placement: "right"; animateFill: false; theme: string; }; }' but required in type 'ForwardRefExoticComponent<TippyProps>'.ts(2741)
```

And below will be fine:

```tsx
export const Popover: React.ForwardRefExoticComponent<TippyProps> = forwardRef(
  props => <Tippy {...props} />
)
```

**Comment by atomiks** [comment]
Ah ok, is there a way to fix those TS types so it's not necessary to do that?

**Comment by KubaJastrz** [comment]
Popover doesn't need `forwardRef`, therefore it shouldn't be typed as exotic component. The following should work:
```tsx
const Popover: React.FunctionComponent<TippyProps> = props => <Tippy {...props} />
```

**Pull request merged**
