### PR TITLE
Use react refs through wrapping the children

### PR DESCRIPTION
**Pull request by MikeDombo**

### CODE REVIEW

**Comment by MikeDombo** [comment]
Using a forwardingRef is the correct solution to this problem, but that requires a bigger API change. This change might be somewhat breaking, depending on if people have styled `<div>` tags.

**Comment by atomiks** [comment]
Can we pass `.firstElementChild` to `tippy()` instead, so we apply the tooltip the actual node instead of the wrapper? Also can't we use `|| 'div'` as shorthand instead of the ternary?

**Comment by atomiks** [comment]
Something like this:

```jsx
<Tippy content="..." strict>
  <button />
</Tippy>
```

So StrictMode users can set `Tippy.defaultProps = { strict: true };`

Implementation:

```jsx
// ...
const REACT_ONLY_PROPS = [
  'children',
  'onCreate',
  'isVisible',
  'isEnabled',
  'tagName',
  'strict'
]

class Tippy extends React.Component {
  state = { isMounted: false }

  node = React.createRef()

  // ...

  componentDidMount() {
    this.setState({ isMounted: true })

    this.tip = tippy.one(
      this.props.strict
        ? this.node.current.firstElementChild
        : ReactDOM.findDOMNode(this),
      this.options
    )
  }

  // ...

  render() {
    return (
      <React.Fragment>
        {this.props.strict
          ? React.createElement(
              this.props.tagName || 'div',
              { ref: this.node },
              this.props.children
            )
          : this.props.children}
        {this.isReactElementContent &&
          this.state.isMounted &&
          ReactDOM.createPortal(this.props.content, this.container)}
      </React.Fragment>
    )
  }
}
```

**Comment by MikeDombo** [comment]
If you're going to make a breaking change, you might as well implement forwarding refs. See: https://reactjs.org/docs/forwarding-refs.html

**Comment by atomiks** [comment]
How do we implement that?

**Comment by MikeDombo** [comment]
After looking through the docs and some examples more. I'm now not sure if that is correct or even possible for this use case.

**Comment by atomiks** [comment]
It seems like `findDOMNode` is the only viable option (without the nasty wrapper hack) unless they add `ref` support to `Fragment`s? See https://twitter.com/sag1v/status/1060598811758915584?s=19

**Comment by MikeDombo** [comment]
Another alternative would be using a render props technique. I haven't actually tried this, but I think it would work.

```
<Tippy content="xxx" render=(ref)=>  <p ref={ref}> Some content</p> />


class Tippy extends React.PureComponent {
  constructor(props) {
    super(props)
    this.ref = React.createRef();
  }

  render() {
    if(this.props.render){
      return this.props.render(this.ref)
    }
    return (
  // Same code that you have right now
);
  }
}
```

**Comment by atomiks** [comment]
That should work with `forwardRef` but every time you use a component child, you need to use render props + `forwardRef` which is so cumbersome compared to just placing the component directly as a child :/

**Comment by MikeDombo** [comment]
If they implement refs on a Fragment, then that would be the best solution. Until they do that, I think the render props is a bit messier in code, but could be better since it doesn't require wrapping in useless dom nodes.

**Comment by MikeDombo** [comment]
I'm not positive that that way requires forwardRef, but maybe it does. That seems like a good way to do it.

**Comment by atomiks** [comment]
See #31

**Pull request closed without merging**
